# Kernel Support Vector Machine

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('social_network_ads.csv');
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size = 0.25)

## Feature scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_fs = sc.fit_transform(X_train)
X_test_fs = sc.transform(X_test)

## Training the kernel SVM model

In [6]:
from sklearn.svm import SVC
classifier = SVC(random_state = 0, probability = True)
# classifier = SVC(random_state = 0, probability = True)
classifier.fit(X_train_fs, y_train)

SVC(probability=True, random_state=0)

## Applying the model on the training set

In [7]:
y_train_re = y_train.reshape(len(y_train), 1)

y_train_pred = classifier.predict(X_train_fs)
y_train_pred = y_train_pred.reshape(len(y_train_pred), 1)

y_train_proba = classifier.predict_proba(X_train_fs)

## Model preformance on the training set

In [8]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, cohen_kappa_score, matthews_corrcoef, roc_auc_score

cm_train = confusion_matrix(y_train, y_train_pred)
cr_train = classification_report(y_train, y_train_pred)
print(cm_train)
print(cr_train)

acc_train = accuracy_score(y_train, y_train_pred)
prec_train = precision_score(y_train, y_train_pred)
ck_train = cohen_kappa_score(y_train, y_train_pred)
mcc_train = matthews_corrcoef(y_train, y_train_pred)
roc_auc_train = roc_auc_score(y_train, y_train_pred)

print(f'Accuracy = {acc_train:.2f}; Precision = {prec_train:.2f}; Kappa = {ck_train:.2f}; MCC = {mcc_train:.2f}; ROC AUC = {roc_auc_train:.2f}')

[[171  18]
 [  8 103]]
              precision    recall  f1-score   support

           0       0.96      0.90      0.93       189
           1       0.85      0.93      0.89       111

    accuracy                           0.91       300
   macro avg       0.90      0.92      0.91       300
weighted avg       0.92      0.91      0.91       300

Accuracy = 0.91; Precision = 0.85; Kappa = 0.82; MCC = 0.82; ROC AUC = 0.92


## Apply the model to a new observations

In [9]:
new_obs = [[37, 87000]]
new_obs_fs = sc.transform(new_obs)

new_obs_pred = classifier.predict(new_obs_fs)
new_obs_pred_proba = classifier.predict_proba(new_obs_fs)
print(new_obs_pred)
print(new_obs_pred_proba)

[0]
[[0.80353319 0.19646681]]


## Apply the model to a test set

In [10]:
y_test_re = y_test.reshape(len(y_test), 1)

y_test_pred = classifier.predict(X_test_fs)
y_test_pred = y_test_pred.reshape(len(y_test_pred), 1)

y_test_proba = classifier.predict_proba(X_test_fs)

## Model performance on the test set

In [14]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, cohen_kappa_score, matthews_corrcoef, roc_auc_score

cm_test = confusion_matrix(y_test, y_test_pred)
cr_test = classification_report(y_test, y_test_pred)
print(cm_test)
print(cr_test)

acc_test = accuracy_score(y_test, y_test_pred)
prec_test = precision_score(y_test, y_test_pred)
ck_test = cohen_kappa_score(y_test, y_test_pred)
mcc_test = matthews_corrcoef(y_test, y_test_pred)
roc_auc_test = roc_auc_score(y_test, y_test_pred)

print(f'Accuracy = {acc_test:.2f}; Precision = {prec_test:.2f}; Kappa = {ck_test:.2f}; MCC = {mcc_test:.2f}; ROC AUC = {roc_auc_test:.2f}')

[[64  4]
 [ 3 29]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95        68
           1       0.88      0.91      0.89        32

    accuracy                           0.93       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100

Accuracy = 0.93; Precision = 0.88; Kappa = 0.84; MCC = 0.84; ROC AUC = 0.92
