# Random forest

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('social_network_ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_fs = sc.fit_transform(X_train)
X_test_fs = sc.transform(X_test)

## Training the random forest model

In [5]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state = 0, criterion = 'entropy', n_estimators = 10)
classifier.fit(X_train_fs, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Applying Random forest on the training set

In [6]:
y_train_re = y_train.reshape(len(y_train), 1)

y_train_pred = classifier.predict(X_train_fs)
y_train_pred = y_train_pred.reshape(len(y_train), 1)

y_train_pred_proba = classifier.predict_proba(X_train_fs)

## Model performance on the training set

In [7]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, matthews_corrcoef, cohen_kappa_score, roc_auc_score

cm_train = confusion_matrix(y_train, y_train_pred)
cr_train = classification_report(y_train, y_train_pred)
print(cm_train)
print(cr_train)

acc_train = accuracy_score(y_train, y_train_pred)
prec_train = precision_score(y_train, y_train_pred)
ck_train = cohen_kappa_score(y_train, y_train_pred)
mcc_train = matthews_corrcoef(y_train, y_train_pred)
roc_auc_train = roc_auc_score(y_train, y_train_pred)

print(f'Accuracy = {acc_train:.2f}; Precision = {prec_train:.2f}; Kappa = {ck_train:.2f}; MCC = {mcc_train:.2f}; ROC AUC = {roc_auc_train:.2f}')

[[187   2]
 [  4 107]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       189
           1       0.98      0.96      0.97       111

    accuracy                           0.98       300
   macro avg       0.98      0.98      0.98       300
weighted avg       0.98      0.98      0.98       300

Accuracy = 0.98; Precision = 0.98; Kappa = 0.96; MCC = 0.96; ROC AUC = 0.98


## Applying random forest to a new onservation

In [8]:
new_obs = [[37, 87000]]
new_obs_fs = sc.transform(new_obs)

new_obs_pred = classifier.predict(new_obs_fs)
new_obs_pred_proba = classifier.predict_proba(new_obs_fs)
print(new_obs_pred)
print(new_obs_pred_proba)

[0]
[[0.6 0.4]]


## Applyng Random forest on the test set

In [9]:
y_test_re = y_test.reshape(len(y_test), 1)

y_test_pred = classifier.predict(X_test_fs)
y_test_pred = y_test_pred.reshape(len(y_test_pred), 1)

y_test_pred_proba = classifier.predict_proba(X_test_fs)

## Model performance on the test set

In [10]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, matthews_corrcoef, cohen_kappa_score, roc_auc_score

cm_test = confusion_matrix(y_test, y_test_pred)
cr_test = classification_report(y_test, y_test_pred)
print(cm_test)
print(cr_test)

acc_test = accuracy_score(y_test, y_test_pred)
prec_test = precision_score(y_test, y_test_pred)
ck_test = cohen_kappa_score(y_test, y_test_pred)
mcc_test = matthews_corrcoef(y_test, y_test_pred)
roc_auc_test = roc_auc_score(y_test, y_test_pred)

print(f'Accuracy = {acc_test:.2f}; Precision = {prec_test:.2f}; Kappa = {ck_test:.2f}; MCC = {mcc_test:.2f}; ROC AUC = {roc_auc_test:.2f}')

[[63  5]
 [ 4 28]]
              precision    recall  f1-score   support

           0       0.94      0.93      0.93        68
           1       0.85      0.88      0.86        32

    accuracy                           0.91       100
   macro avg       0.89      0.90      0.90       100
weighted avg       0.91      0.91      0.91       100

Accuracy = 0.91; Precision = 0.85; Kappa = 0.79; MCC = 0.80; ROC AUC = 0.90
