# Support Vector Machine

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('social_network_ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size = 0.25)

## Feature scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_fs = sc.fit_transform(X_train)
X_test_fs = sc.transform(X_test)

## Training the SVM model

In [5]:
from sklearn.svm import SVC
classifier = SVC(random_state = 0, kernel = 'linear', probability = True)
# classifier = SVC(random_state = 0, probability = True)
classifier.fit(X_train_fs, y_train)

SVC(kernel='linear', probability=True, random_state=0)

## Applying the SVM model on the train set

In [6]:
y_train_re = y_train.reshape(len(y_train), 1)

y_train_pred = classifier.predict(X_train_fs)
y_train_pred = y_train_pred.reshape(len(y_train_pred), 1)

y_train_proba = classifier.predict_proba(X_train_fs)

## Model performance on the training set

In [7]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, cohen_kappa_score, matthews_corrcoef, roc_auc_score

cm_train = confusion_matrix(y_train, y_train_pred)
cr_train = classification_report(y_train, y_train_pred)
print(cm_train)
print(cr_train)

acc_train = accuracy_score(y_train, y_train_pred)
prec_train = precision_score(y_train, y_train_pred)
ck_train = cohen_kappa_score(y_train, y_train_pred)
mcc_train = matthews_corrcoef(y_train, y_train_pred)
roc_auc_train = roc_auc_score(y_train, y_train_pred)

print(f'Accuracy = {acc_train:.2f}; Precision = {prec_train:.2f}; Kappa = {ck_train:.2f}; MCC = {mcc_train:.2f}; ROC AUC = {roc_auc_train:.2f}')

[[173  16]
 [ 37  74]]
              precision    recall  f1-score   support

           0       0.82      0.92      0.87       189
           1       0.82      0.67      0.74       111

    accuracy                           0.82       300
   macro avg       0.82      0.79      0.80       300
weighted avg       0.82      0.82      0.82       300

Accuracy = 0.82; Precision = 0.82; Kappa = 0.61; MCC = 0.61; ROC AUC = 0.79


## Apply the model to a new observations

In [8]:
new_obs = [[37, 87000]]
new_obs_fs = sc.transform(new_obs)

new_obs_pred = classifier.predict(new_obs_fs)
new_obs_pred_proba = classifier.predict_proba(new_obs_fs)
print(new_obs_pred)
print(new_obs_pred_proba)

[0]
[[0.62907928 0.37092072]]


## Apply the model to the test set

In [9]:
y_test_re = y_test.reshape(len(y_test), 1)

y_test_pred = classifier.predict(X_test_fs)
y_test_pred = y_test_pred.reshape(len(y_test_pred), 1)

y_test_proba = classifier.predict_proba(X_test_fs)

## Model performance on the test set

In [11]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, cohen_kappa_score, matthews_corrcoef, roc_auc_score

cm_test = confusion_matrix(y_test, y_test_pred)
cr_test = classification_report(y_test, y_test_pred)
print(cm_test)
print(cr_test)

acc_test = accuracy_score(y_test, y_test_pred)
prec_test = precision_score(y_test, y_test_pred)
ck_test = cohen_kappa_score(y_test, y_test_pred)
mcc_test = matthews_corrcoef(y_test, y_test_pred)
roc_auc_test = roc_auc_score(y_test, y_test_pred)

print(f'Accuracy = {acc_test:.2f}; Precision = {prec_test:.2f}; Kappa = {ck_test:.2f}; MCC = {mcc_test:.2f}; ROC AUC = {roc_auc_test:.2f}')

[[66  2]
 [ 8 24]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93        68
           1       0.92      0.75      0.83        32

    accuracy                           0.90       100
   macro avg       0.91      0.86      0.88       100
weighted avg       0.90      0.90      0.90       100

Accuracy = 0.90; Precision = 0.92; Kappa = 0.76; MCC = 0.77; ROC AUC = 0.86
