# Artificial Neural Networks

## Part 1: Data preprocessing

### 1. Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# tf.__version__
# from tensorflow.python.client import device_lib
# print(device_lib.list_local_devices())

### 2. Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


### 3. Transform categorical data

#### 3.1. Label Encoding the "Gender" column

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### 3.2. One Hot Encoding the "Geography" column

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### 4. Splitting the dataset

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

### 5. Feature scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-0.99850112  1.71490137 -0.57273139 ... -1.55337352  0.97725852
   0.42739449]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352 -1.02327069
  -1.02548708]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.94479772]
 ...
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.14096853]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
   0.01781218]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017 -1.02327069
  -1.15822478]]


## Part 2: Initializing the ANN

### 1. Initializing the ANN

In [8]:
ann = tf.keras.models.Sequential()

### 2. Adding the input and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### 3. Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### 4. Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3. Training the ANN

### 1. Compiling the ANN

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### 2. Training the ANN on the train set

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5252 - accuracy: 0.7972
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4661 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4432 - accuracy: 0.7971
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4304 - accuracy: 0.8031
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4218 - accuracy: 0.8185
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4139 - accuracy: 0.8279
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4052 - accuracy: 0.8329
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3974 - accuracy: 0.8371
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3893 - accuracy: 0.8401
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3799 - accura

250/250 [==============================] - 1s 4ms/step - loss: 0.3357 - accuracy: 0.8609
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3357 - accuracy: 0.8601
Epoch 83/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3353 - accuracy: 0.8620
Epoch 84/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3357 - accuracy: 0.8600
Epoch 85/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3355 - accuracy: 0.8615
Epoch 86/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3356 - accuracy: 0.8619: 0s - loss:
Epoch 87/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3350 - accuracy: 0.8609
Epoch 88/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3350 - accuracy: 0.8601: 0s - loss: 0
Epoch 89/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3353 - accuracy: 0.8620
Epoch 90/100
250/250 [==============================] - 1s 4ms/step -

### 3. TODO: Apply model on the train set

In [14]:
# TODO:

## Part 4: Making the predictions and evaluating the model

### 1. Predicting the result of a single observation

#### Homework

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?


#### Solution

In [15]:
test_object = [[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]
test_object = sc.transform(test_object)
test_object_pred = ann.predict(test_object)
print(test_object_pred[0, 0])
if test_object_pred > 0.5:
    print('The client is going to leave the bank.')
else:
    print('The client is not going to leave the bank.')

0.030268995
The client is not going to leave the bank.


### 2. Apply model to the test set

In [16]:
y_test_pred = ann.predict(X_test)
y_test_pred = y_test_pred.reshape(len(y_test_pred))

for i in range(0, len(y_test_pred)):
    y_test_pred[i] = int(y_test_pred[i] > 0.5)


### 3. Evaluating the model performance on the test set

In [17]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_test, y_test_pred)
cr = classification_report(y_test, y_test_pred)
print(cm)
print(cr)

[[1523   62]
 [ 214  201]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1585
           1       0.76      0.48      0.59       415

    accuracy                           0.86      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000



In [18]:
from sklearn.metrics import accuracy_score, precision_score, cohen_kappa_score, matthews_corrcoef, roc_auc_score

acc_test = accuracy_score(y_test, y_test_pred)
prec_test = precision_score(y_test, y_test_pred)
ck_test = cohen_kappa_score(y_test, y_test_pred)
mcc_test = matthews_corrcoef(y_test, y_test_pred)
roc_auc_test = roc_auc_score(y_test, y_test_pred)

print(f'Accuracy = {acc_test:.2f}; Precision = {prec_test:.2f}; Kappa = {ck_test:.2f}; MCC = {mcc_test:.2f}; ROC AUC = {roc_auc_test:.2f}')

Accuracy = 0.86; Precision = 0.76; Kappa = 0.51; MCC = 0.53; ROC AUC = 0.72
