# Classifiers

## Preprocessing

### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the libraries for evaluating model's performance
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, cohen_kappa_score, matthews_corrcoef, roc_auc_score

### Importing the dataset

In [2]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Splitting the dataset

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

y_train_re = y_train.reshape(len(y_train), 1)

### Feature scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_fs = sc.fit_transform(X_train)
X_test_fs = sc.transform(X_test)

## Logistic regression

### Create model

In [5]:
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 0)

### Training the model

In [6]:
lr_classifier.fit(X_train_fs, y_train)

LogisticRegression(random_state=0)

### Applying the model on the train test

In [7]:
lr_y_train_pred = lr_classifier.predict(X_train_fs)
lr_y_train_pred = lr_y_train_pred.reshape(len(lr_y_train_pred), 1)

### Evaluating the model performance on the train set

In [8]:
lr_cm_train = confusion_matrix(y_train, lr_y_train_pred)
lr_cr_train = classification_report(y_train, lr_y_train_pred)

print(lr_cm_train)
print(lr_cr_train)

[[332   5]
 [  5 170]]
              precision    recall  f1-score   support

           2       0.99      0.99      0.99       337
           4       0.97      0.97      0.97       175

    accuracy                           0.98       512
   macro avg       0.98      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512



In [9]:
lr_acc_train = accuracy_score(y_train, lr_y_train_pred)
lr_prec_train = precision_score(y_train, lr_y_train_pred, pos_label=2)
lr_ck_train = cohen_kappa_score(y_train, lr_y_train_pred)
lr_mcc_train = matthews_corrcoef(y_train, lr_y_train_pred)
lr_roc_auc_train = roc_auc_score(y_train, lr_y_train_pred)

print(f'Accuracy = {lr_acc_train:.2f}; Precision = {lr_prec_train:.2f}; Kappa = {lr_ck_train:.2f}; MCC = {lr_mcc_train:.2f}; ROC AUC = {lr_roc_auc_train:.2f}')

Accuracy = 0.98; Precision = 0.99; Kappa = 0.96; MCC = 0.96; ROC AUC = 0.98


### Applying the model on the test set

In [10]:
lr_y_test_pred = lr_classifier.predict(X_test_fs)
lr_y_test_pred = lr_y_test_pred.reshape(len(lr_y_test_pred), 1)

### Evaluating the model performance on the test set

In [11]:
lr_cm_test = confusion_matrix(y_test, lr_y_test_pred)
lr_cr_test = classification_report(y_test, lr_y_test_pred)

print(lr_cm_test)
print(lr_cr_test)

[[103   4]
 [  5  59]]
              precision    recall  f1-score   support

           2       0.95      0.96      0.96       107
           4       0.94      0.92      0.93        64

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171



In [71]:
lr_acc_test = accuracy_score(y_test, lr_y_test_pred)
lr_prec_test = precision_score(y_test, lr_y_test_pred, pos_label = 2)
lr_ck_test = cohen_kappa_score(y_test, lr_y_test_pred)
lr_mcc_test = matthews_corrcoef(y_test, lr_y_test_pred)
lr_roc_auc_test = roc_auc_score(y_test, lr_y_test_pred)

print(f'Accuracy = {lr_acc_test:.2f}; Precision = {lr_prec_test:.2f}; Kappa = {lr_ck_test:.2f}; MCC = {lr_mcc_test:.2f}; ROC AUC = {lr_roc_auc_test:.2f}')
print(f'Accuracy = {lr_acc_test}')

Accuracy = 0.95; Precision = 0.95; Kappa = 0.89; MCC = 0.89; ROC AUC = 0.94
Accuracy = 0.9473684210526315


## k-Nearest neighbor

### Create model

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 5, p = 2, metric = "minkowski")

### Training the model

In [14]:
knn_classifier.fit(X_train_fs, y_train)

KNeighborsClassifier()

### Applying the kNN model to the training set

In [15]:
knn_y_train_pred = knn_classifier.predict(X_train_fs)
knn_y_train_pred = knn_y_train_pred.reshape(len(knn_y_train_pred), 1)

### Evaluating the model performance on the train set

In [16]:
knn_cm_train = confusion_matrix(y_train, knn_y_train_pred)
knn_cr_train = classification_report(y_train, knn_y_train_pred)

print(knn_cm_train)
print(knn_cr_train)

[[331   6]
 [  6 169]]
              precision    recall  f1-score   support

           2       0.98      0.98      0.98       337
           4       0.97      0.97      0.97       175

    accuracy                           0.98       512
   macro avg       0.97      0.97      0.97       512
weighted avg       0.98      0.98      0.98       512



In [17]:
knn_acc_train = accuracy_score(y_train, knn_y_train_pred)
knn_prec_train = precision_score(y_train, knn_y_train_pred, pos_label = 2)
knn_ck_train = cohen_kappa_score(y_train, knn_y_train_pred)
knn_mcc_train = matthews_corrcoef(y_train, knn_y_train_pred)
knn_roc_auc_train = roc_auc_score(y_train, knn_y_train_pred)

print(f'Accuracy = {knn_acc_train:.2f}; Precision = {knn_prec_train:.2f}; Kappa = {knn_ck_train:.2f}; MCC = {knn_mcc_train:.2f}; ROC AUC = {knn_roc_auc_train:.2f}')

Accuracy = 0.98; Precision = 0.98; Kappa = 0.95; MCC = 0.95; ROC AUC = 0.97


### Applying the model on the test set

In [18]:
knn_y_test_pred = knn_classifier.predict(X_test_fs)
knn_y_test_pred = knn_y_test_pred.reshape(len(knn_y_test_pred), 1)

### Evaluating the model performance on the test set

In [19]:
knn_cm_test = confusion_matrix(y_test, knn_y_test_pred)
knn_cr_test = classification_report(y_test, knn_y_test_pred)

print(knn_cm_test)
print(knn_cr_test)

[[103   4]
 [  5  59]]
              precision    recall  f1-score   support

           2       0.95      0.96      0.96       107
           4       0.94      0.92      0.93        64

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171



In [72]:
knn_acc_test = accuracy_score(y_test, knn_y_test_pred)
knn_prec_test = precision_score(y_test, knn_y_test_pred, pos_label = 2)
knn_ck_test = cohen_kappa_score(y_test, knn_y_test_pred)
knn_mcc_test = matthews_corrcoef(y_test, knn_y_test_pred)
knn_roc_auc_test = roc_auc_score(y_test, knn_y_test_pred)

print(f'Accuracy = {knn_acc_test:.2f}; Precision = {knn_prec_test:.2f}; Kappa = {knn_ck_test:.2f}; MCC = {knn_mcc_test:.2f}; ROC AUC = {knn_roc_auc_test:.2f}')
print(f'Accuracy = {knn_acc_test}')

Accuracy = 0.95; Precision = 0.95; Kappa = 0.89; MCC = 0.89; ROC AUC = 0.94
Accuracy = 0.9473684210526315


## Support vector machines

### Create the model

In [21]:
from sklearn.svm import SVC
svml_classifier = SVC(random_state = 0, kernel = 'linear', probability = True)

### Training the model

In [22]:
svml_classifier.fit(X_train_fs, y_train)

SVC(kernel='linear', probability=True, random_state=0)

### Applying the model on the train set

In [23]:
svml_y_train_pred = svml_classifier.predict(X_train_fs)
svml_y_train_pred = svml_y_train_pred.reshape(len(svml_y_train_pred), 1)

### Evaluating the model performance on the train set

In [24]:
svml_cm_train = confusion_matrix(y_train, svml_y_train_pred)
svml_cr_train = classification_report(y_train, svml_y_train_pred)

print(svml_cm_train)
print(svml_cr_train)

[[330   7]
 [  3 172]]
              precision    recall  f1-score   support

           2       0.99      0.98      0.99       337
           4       0.96      0.98      0.97       175

    accuracy                           0.98       512
   macro avg       0.98      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512



In [25]:
svml_acc_train = accuracy_score(y_train, svml_y_train_pred)
svml_prec_train = precision_score(y_train, svml_y_train_pred, pos_label = 4)
svml_ck_train = cohen_kappa_score(y_train, svml_y_train_pred)
svml_mcc_train = matthews_corrcoef(y_train, svml_y_train_pred)
svml_roc_auc_train = roc_auc_score(y_train, svml_y_train_pred)

print(f'Accuracy = {svml_acc_train:.2f}; Precision = {svml_prec_train:.2f}; Kappa = {svml_ck_train:.2f}; MCC = {svml_mcc_train:.2f}; ROC AUC = {svml_roc_auc_train:.2f}')

Accuracy = 0.98; Precision = 0.96; Kappa = 0.96; MCC = 0.96; ROC AUC = 0.98


### Applying the model on the test set

In [26]:
svml_y_test_pred = svml_classifier.predict(X_test_fs)
svml_y_test_pred = svml_y_test_pred.reshape(len(svml_y_test_pred), 1)

### Evaluating the model performance on the test set

In [27]:
svml_cm_test = confusion_matrix(y_test, svml_y_test_pred)
svml_cr_test = classification_report(y_test, svml_y_test_pred)

print(svml_cm_test)
print(svml_cr_test)

[[102   5]
 [  5  59]]
              precision    recall  f1-score   support

           2       0.95      0.95      0.95       107
           4       0.92      0.92      0.92        64

    accuracy                           0.94       171
   macro avg       0.94      0.94      0.94       171
weighted avg       0.94      0.94      0.94       171



In [73]:
svml_acc_test = accuracy_score(y_test, svml_y_test_pred)
svml_prec_test = precision_score(y_test, svml_y_test_pred, pos_label = 2)
svml_ck_test = cohen_kappa_score(y_test, svml_y_test_pred)
svml_mcc_test = matthews_corrcoef(y_test, svml_y_test_pred)
svml_roc_auc_test = roc_auc_score(y_test, svml_y_test_pred)

print(f'Accuracy = {svml_acc_test:.2f}; Precision = {svml_prec_test:.2f}; Kappa = {svml_ck_test:.2f}; MCC = {svml_mcc_test:.2f}; ROC AUC = {svml_roc_auc_test:.2f}')
print(f'Accuracy = {svml_acc_test}')

Accuracy = 0.94; Precision = 0.95; Kappa = 0.88; MCC = 0.88; ROC AUC = 0.94
Accuracy = 0.9415204678362573


## Kernel Support Vector Machines

### Creating the model

In [29]:
from sklearn.svm import SVC
svmk_classifier = SVC(random_state = 0, probability = True)

### Training the model

In [30]:
svmk_classifier.fit(X_train_fs, y_train)

SVC(probability=True, random_state=0)

### Applying the model on the train test

In [31]:
svmk_y_train_pred = svmk_classifier.predict(X_train_fs)
svmk_y_train_pred = svmk_y_train_pred.reshape(len(svmk_y_train_pred), 1)

### Evaluating the model performance on the train set

In [32]:
svmk_cm_train = confusion_matrix(y_train, svmk_y_train_pred)
svmk_cr_train = classification_report(y_train, svmk_y_train_pred)

print(svmk_cm_train)
print(svmk_cr_train)

[[330   7]
 [  4 171]]
              precision    recall  f1-score   support

           2       0.99      0.98      0.98       337
           4       0.96      0.98      0.97       175

    accuracy                           0.98       512
   macro avg       0.97      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512



In [33]:
svmk_acc_train = accuracy_score(y_train, svmk_y_train_pred)
svmk_prec_train = precision_score(y_train, svmk_y_train_pred, pos_label = 2)
svmk_ck_train = cohen_kappa_score(y_train, svmk_y_train_pred)
svmk_mcc_train = matthews_corrcoef(y_train, svmk_y_train_pred)
svmk_roc_auc_train = roc_auc_score(y_train, svmk_y_train_pred)

print(f'Accuracy = {svmk_acc_train:.2f}; Precision = {svmk_prec_train:.2f}; Kappa = {svmk_ck_train:.2f}; MCC = {svmk_mcc_train:.2f}; ROC AUC = {svmk_roc_auc_train:.2f}')

Accuracy = 0.98; Precision = 0.99; Kappa = 0.95; MCC = 0.95; ROC AUC = 0.98


### Applying the model on the test test

In [34]:
svmk_y_test_pred = svmk_classifier.predict(X_test_fs)
svmk_y_test_pred = svmk_y_test_pred.reshape(len(svmk_y_test_pred), 1)

### Evaluating the model performance on the test set

In [35]:
svmk_cm_test = confusion_matrix(y_test, svmk_y_test_pred)
svmk_cr_test = classification_report(y_test, svmk_y_test_pred)

print(svmk_cm_test)
print(svmk_cr_test)

[[102   5]
 [  3  61]]
              precision    recall  f1-score   support

           2       0.97      0.95      0.96       107
           4       0.92      0.95      0.94        64

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [74]:
svmk_acc_test = accuracy_score(y_test, svmk_y_test_pred)
svmk_prec_test = precision_score(y_test, svmk_y_test_pred, pos_label = 2)
svmk_ck_test = cohen_kappa_score(y_test, svmk_y_test_pred)
svmk_mcc_test = matthews_corrcoef(y_test, svmk_y_test_pred)
svmk_roc_auc_test = roc_auc_score(y_test, svmk_y_test_pred)

print(f'Accuracy = {svmk_acc_test:.2f}; Precision = {svmk_prec_test:.2f}; Kappa = {svmk_ck_test:.2f}; MCC = {svmk_mcc_test:.2f}; ROC AUC = {svmk_roc_auc_test:.2f}')
print(f'Accuracy = {svmk_acc_test}')

Accuracy = 0.95; Precision = 0.97; Kappa = 0.90; MCC = 0.90; ROC AUC = 0.95
Accuracy = 0.9532163742690059


## Naive Bayes

### Creating the model

In [37]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()

### Training the model

In [38]:
nb_classifier.fit(X_train_fs, y_train)

GaussianNB()

### Applying the model on the train set

In [39]:
nb_y_train_pred = nb_classifier.predict(X_train_fs)
nb_y_train_pred = nb_y_train_pred.reshape(len(nb_y_train_pred), 1)

### Evaluating the model performance on the train set

In [40]:
nb_cm_train = confusion_matrix(y_train, nb_y_train_pred)
nb_cr_train = classification_report(y_train, nb_y_train_pred)

print(nb_cm_train)
print(nb_cr_train)

[[324  13]
 [  3 172]]
              precision    recall  f1-score   support

           2       0.99      0.96      0.98       337
           4       0.93      0.98      0.96       175

    accuracy                           0.97       512
   macro avg       0.96      0.97      0.97       512
weighted avg       0.97      0.97      0.97       512



In [41]:
nb_acc_train = accuracy_score(y_train, nb_y_train_pred)
nb_prec_train = precision_score(y_train, nb_y_train_pred, pos_label = 2)
nb_ck_train = cohen_kappa_score(y_train, nb_y_train_pred)
nb_mcc_train = matthews_corrcoef(y_train, nb_y_train_pred)
nb_roc_auc_train = roc_auc_score(y_train, nb_y_train_pred)

print(f'Accuracy = {nb_acc_train:.2f}; Precision = {nb_prec_train:.2f}; Kappa = {nb_ck_train:.2f}; MCC = {nb_mcc_train:.2f}; ROC AUC = {nb_roc_auc_train:.2f}')

Accuracy = 0.97; Precision = 0.99; Kappa = 0.93; MCC = 0.93; ROC AUC = 0.97


### Applying the model on the test set

In [42]:
nb_y_test_pred = nb_classifier.predict(X_test_fs)
nb_y_test_pred = nb_y_test_pred.reshape(len(nb_y_test_pred), 1)

### Evaluating the model performance on the test set

In [43]:
nb_cm_test = confusion_matrix(y_test, nb_y_test_pred)
nb_cr_test = classification_report(y_test, nb_y_test_pred)

print(nb_cm_test)
print(nb_cr_test)

[[99  8]
 [ 2 62]]
              precision    recall  f1-score   support

           2       0.98      0.93      0.95       107
           4       0.89      0.97      0.93        64

    accuracy                           0.94       171
   macro avg       0.93      0.95      0.94       171
weighted avg       0.94      0.94      0.94       171



In [75]:
nb_acc_test = accuracy_score(y_test, nb_y_test_pred)
nb_prec_test = precision_score(y_test, nb_y_test_pred, pos_label = 2)
nb_ck_test = cohen_kappa_score(y_test, nb_y_test_pred)
nb_mcc_test = matthews_corrcoef(y_test, nb_y_test_pred)
nb_roc_auc_test = roc_auc_score(y_test, nb_y_test_pred)

print(f'Accuracy = {nb_acc_test:.2f}; Precision = {nb_prec_test:.2f}; Kappa = {nb_ck_test:.2f}; MCC = {nb_mcc_test:.2f}; ROC AUC = {nb_roc_auc_test:.2f}')
print(f'Accuracy = {nb_acc_test}')

Accuracy = 0.94; Precision = 0.98; Kappa = 0.88; MCC = 0.88; ROC AUC = 0.95
Accuracy = 0.9415204678362573


## Decision Tree

### Creating the model

In [45]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(random_state = 0, criterion = 'entropy')

### Training the model

In [47]:
dt_classifier.fit(X_train_fs, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

### Applying the model on the train set

In [48]:
dt_y_train_pred = dt_classifier.predict(X_train_fs)
dt_y_train_pred = dt_y_train_pred.reshape(len(dt_y_train_pred), 1)

### Evaluating the model performance on the train set

In [50]:
dt_cm_train = confusion_matrix(y_train, dt_y_train_pred)
dt_cr_train = classification_report(y_train, dt_y_train_pred)

print(dt_cm_train)
print(dt_cr_train)

[[337   0]
 [  0 175]]
              precision    recall  f1-score   support

           2       1.00      1.00      1.00       337
           4       1.00      1.00      1.00       175

    accuracy                           1.00       512
   macro avg       1.00      1.00      1.00       512
weighted avg       1.00      1.00      1.00       512



In [52]:
dt_acc_train = accuracy_score(y_train, dt_y_train_pred)
dt_prec_train = precision_score(y_train, dt_y_train_pred, pos_label = 2)
dt_ck_train = cohen_kappa_score(y_train, dt_y_train_pred)
dt_mcc_train = matthews_corrcoef(y_train, dt_y_train_pred)
dt_roc_auc_train = roc_auc_score(y_train, dt_y_train_pred)

print(f'Accuracy = {dt_acc_train:.2f}; Precision = {dt_prec_train:.2f}; Kappa = {dt_ck_train:.2f}; MCC = {dt_mcc_train:.2f}; ROC AUC = {dt_roc_auc_train:.2f}')

Accuracy = 1.00; Precision = 1.00; Kappa = 1.00; MCC = 1.00; ROC AUC = 1.00


### Applying the model on the test set

In [53]:
dt_y_test_pred = dt_classifier.predict(X_test_fs)
dt_y_test_pred = dt_y_test_pred.reshape(len(dt_y_test_pred), 1)

### Evaluating the model performance on the test set

In [55]:
dt_cm_test = confusion_matrix(y_test, dt_y_test_pred)
dt_cr_test = classification_report(y_test, dt_y_test_pred)

print(dt_cm_test)
print(dt_cr_test)

[[103   4]
 [  3  61]]
              precision    recall  f1-score   support

           2       0.97      0.96      0.97       107
           4       0.94      0.95      0.95        64

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [76]:
dt_acc_test = accuracy_score(y_test, dt_y_test_pred)
dt_prec_test = precision_score(y_test, dt_y_test_pred, pos_label = 2)
dt_ck_test = cohen_kappa_score(y_test, dt_y_test_pred)
dt_mcc_test = matthews_corrcoef(y_test, dt_y_test_pred)
dt_roc_auc_test = roc_auc_score(y_test, dt_y_test_pred)

print(f'Accuracy = {dt_acc_test:.2f}; Precision = {dt_prec_test:.2f}; Kappa = {dt_ck_test:.2f}; MCC = {dt_mcc_test:.2f}; ROC AUC = {dt_roc_auc_test:.2f}')
print(f'Accuracy = {dt_acc_test}')

Accuracy = 0.96; Precision = 0.97; Kappa = 0.91; MCC = 0.91; ROC AUC = 0.96
Accuracy = 0.9590643274853801


## Random forest

### Creating the model

In [58]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(random_state = 0, criterion = 'entropy', n_estimators = 10)

### Training the model

In [59]:
rf_classifier.fit(X_train_fs, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

### Applying the model on the train set

In [62]:
rf_y_train_pred = rf_classifier.predict(X_train_fs)
rf_y_train_pred = rf_y_train_pred.reshape(len(rf_y_train_pred), 1)

### Evaluating the model performance on the train set

In [63]:
rf_cm_train = confusion_matrix(y_train, rf_y_train_pred)
rf_cr_train = classification_report(y_train, rf_y_train_pred)

print(rf_cm_train)
print(rf_cr_train)

[[336   1]
 [  1 174]]
              precision    recall  f1-score   support

           2       1.00      1.00      1.00       337
           4       0.99      0.99      0.99       175

    accuracy                           1.00       512
   macro avg       1.00      1.00      1.00       512
weighted avg       1.00      1.00      1.00       512



In [66]:
rf_acc_train = accuracy_score(y_train, rf_y_train_pred)
rf_prec_train = precision_score(y_train, rf_y_train_pred, pos_label = 2)
rf_ck_train = cohen_kappa_score(y_train, rf_y_train_pred)
rf_mcc_train = matthews_corrcoef(y_train, rf_y_train_pred)
rf_roc_auc_train = roc_auc_score(y_train, rf_y_train_pred)

print(f'Accuracy = {rf_acc_train:.2f}; Precision = {rf_prec_train:.2f}; Kappa = {rf_ck_train:.2f}; MCC = {rf_mcc_train:.2f}; ROC AUC = {rf_roc_auc_train:.2f}')

Accuracy = 1.00; Precision = 1.00; Kappa = 0.99; MCC = 0.99; ROC AUC = 1.00


### Applying the model on the test set

In [68]:
rf_y_test_pred = rf_classifier.predict(X_test_fs)
rf_y_test_pred = rf_y_test_pred.reshape(len(rf_y_test_pred), 1)

### Evaluating the model performance on the test set

In [69]:
rf_cm_test = confusion_matrix(y_test, rf_y_test_pred)
rf_cr_test = classification_report(y_test, rf_y_test_pred)

print(rf_cm_test)
print(rf_cr_test)

[[102   5]
 [  6  58]]
              precision    recall  f1-score   support

           2       0.94      0.95      0.95       107
           4       0.92      0.91      0.91        64

    accuracy                           0.94       171
   macro avg       0.93      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171



In [77]:
rf_acc_test = accuracy_score(y_test, rf_y_test_pred)
rf_prec_test = precision_score(y_test, rf_y_test_pred, pos_label = 2)
rf_ck_test = cohen_kappa_score(y_test, rf_y_test_pred)
rf_mcc_test = matthews_corrcoef(y_test, rf_y_test_pred)
rf_roc_auc_test = roc_auc_score(y_test, rf_y_test_pred)

print(f'Accuracy = {rf_acc_test:.2f}; Precision = {rf_prec_test:.2f}; Kappa = {rf_ck_test:.2f}; MCC = {rf_mcc_test:.2f}; ROC AUC = {rf_roc_auc_test:.2f}')
print(f'Accuracy = {rf_acc_test}')

Accuracy = 0.94; Precision = 0.94; Kappa = 0.86; MCC = 0.86; ROC AUC = 0.93
Accuracy = 0.935672514619883
