# Linear Discriminant Analysis

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('wine.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
#

## Splitting the dataset

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_fs = sc.fit_transform(X_train)
X_test_fs = sc.transform(X_test)

## Applying the LDA

In [9]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components = 2)
X_train_lda = lda.fit_transform(X_train_fs, y_train)
X_test_lda = lda.transform(X_test_fs)

## Training a logistic regression on the train set

In [10]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_lda, y_train)

LogisticRegression()

## Applying the logistic regression on the train set

In [12]:
y_train_re = y_train.reshape(len(y_train), 1)

y_train_pred = classifier.predict(X_train_lda)
# y_train_pred = classifier.predict(X_train_fs)
y_train_pred = y_train_pred.reshape(len(y_train_pred), 1)

y_train_pred_proba = classifier.predict_proba(X_train_lda)
# y_train_pred_proba = classifier.predict_proba(X_train_fs)

## Model performance on the train set

In [13]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, matthews_corrcoef, cohen_kappa_score, roc_auc_score

cm_train = confusion_matrix(y_train, y_train_pred)
cr_train = classification_report(y_train, y_train_pred)
print(cm_train)
print(cr_train)

acc_train = accuracy_score(y_train, y_train_pred)
# prec_train = precision_score(y_train, y_train_pred)
ck_train = cohen_kappa_score(y_train, y_train_pred)
mcc_train = matthews_corrcoef(y_train, y_train_pred)
# roc_auc_train = roc_auc_score(y_train, y_train_pred)
# print(f'Accuracy = {acc_train:.2f}; Precision = {prec_train:.2f}; Kappa = {ck_train:.2f}; MCC = {mcc_train:.2f}; ROC AUC = {roc_auc_train:.2f}')
print(f'Accuracy = {acc_train:.2f}; Kappa = {ck_train:.2f}; MCC = {mcc_train:.2f}')

[[45  0  0]
 [ 0 55  0]
 [ 0  0 42]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        45
           2       1.00      1.00      1.00        55
           3       1.00      1.00      1.00        42

    accuracy                           1.00       142
   macro avg       1.00      1.00      1.00       142
weighted avg       1.00      1.00      1.00       142

Accuracy = 1.00; Kappa = 1.00; MCC = 1.00


## Applying the logistic regression to the test set

In [14]:
y_test_re = y_test.reshape(len(y_test), 1)

y_test_pred = classifier.predict(X_test_lda)
# y_test_pred = classifier.predict(X_test_fs)
y_test_pred = y_test_pred.reshape(len(y_test_pred), 1)

y_test_pred_proba = classifier.predict_proba(X_test_lda)
# y_test_pred_proba = classifier.predict_proba(X_test_fs)

## Model performance on the test set

In [15]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, matthews_corrcoef, cohen_kappa_score, roc_auc_score

cm_test = confusion_matrix(y_test, y_test_pred)
cr_test = classification_report(y_test, y_test_pred)
print(cm_test)
print(cr_test)

acc_test = accuracy_score(y_test, y_test_pred)
# prec_test = precision_score(y_test, y_test_pred)
ck_test = cohen_kappa_score(y_test, y_test_pred)
mcc_test = matthews_corrcoef(y_test, y_test_pred)
# roc_auc_test = roc_auc_score(y_test, y_test_pred)
# print(f'Accuracy = {acc_test:.2f}; Precision = {prec_test:.2f}; Kappa = {ck_test:.2f}; MCC = {mcc_test:.2f}; ROC AUC = {roc_auc_test:.2f}')
print(f'Accuracy = {acc_test:.2f}; Kappa = {ck_test:.2f}; MCC = {mcc_test:.2f}')

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00         6

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

Accuracy = 1.00; Kappa = 1.00; MCC = 1.00
